version: '3.8'

services:
  scanner-api:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scan-results:/app/results
    networks:
      - scanner-network

  nmap:
    image: instrumentisto/nmap:latest
    command: tail -f /dev/null
    networks:
      - scanner-network

  nuclei:
    image: projectdiscovery/nuclei:latest
    command: tail -f /dev/null
    volumes:
      - ./scan-results:/results
    networks:
      - scanner-network

  owasp-zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=scanner-api-key
    ports:
      - "8080:8080"
    networks:
      - scanner-network

  sslyze:
    image: python:3.11-slim
    command: tail -f /dev/null
    volumes:
      - ./scan-results:/results
    entrypoint: /bin/bash -c "pip install sslyze && tail -f /dev/null"
    networks:
      - scanner-network

networks:
  scanner-network:
    driver: bridge
