version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    volumes:
      - ./backend:/app
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - scanner-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - scanner-network
    restart: unless-stopped

networks:
  scanner-network:
    driver: bridge
